### ISSUE TITLE
Neos 5.3 Support would be nice

### ISSUE THREAD

**Issue by paavo** [beromir/Beromir.Ray#1]

**Comment by beromir** [comment]
I will test it in the next few days.

The only requirement for the Ray package is PHP 7.3+.
https://spatie.be/docs/ray/v1/requirements

If Neos 5.3 runs on PHP 7.3+, it should probably work fine.

**Comment by beromir** [comment]
The package is compatible with PHP 7.3 and Neos 5.3 with the latest version.

I look forward to your feedback if you encounter any problems or have any new feature requests.
